//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoWeb2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.RoleMenu = new HashSet<RoleMenu>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int MenuGroupId { get; set; }
        public int SortOrder { get; set; }
    
        public virtual MenuGroup MenuGroup { get; set; }
        public virtual ICollection<RoleMenu> RoleMenu { get; set; }
    }
}
